#!/bin/sh
sudo chmod o=rw /dev/ttyACM${PORT_NO:-3}

# Copy sw contents to /
cd sw
rshell -p /dev/ttyACM${PORT_NO:-3} --buffer-size 512 cp *.py "/pyboard/"
[ "$1" = "-f" ] && rshell -p /dev/ttyACM${PORT_NO:-3} --buffer-size 512 cp -r libs/ "/pyboard/"
[ "$1" = "-f" ] && rshell -p /dev/ttyACM${PORT_NO:-3} --buffer-size 512 cp -r line_follower/ "/pyboard/"

# Copy Subsystems/ to /
cd ..
rshell -p /dev/ttyACM${PORT_NO:-3} --buffer-size 512 cp -r Subsystems/ "/pyboard/"

# Run from soft boot
rshell -p /dev/ttyACM${PORT_NO:-3} --buffer-size 512 repl
